// Code generated by protoc-gen-tars. DO NOT EDIT.
// source: OtpVerifyServer.proto

/*
Package UdbApp_OtpVerifyServer is a generated protocol buffer package.

It is generated from these files:
	OtpVerifyServer.proto

It has these top-level messages:
	Request
	Response
	AuthorizeMsg
	OtpVerifyReq
	OtpVerifyRsp
*/
package UdbApp_OtpVerifyServer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	"code.yy.com/yytars/goframework/tars/servant"
	"code.yy.com/yytars/goframework/tars/servant/model"
	"code.yy.com/yytars/goframework/jce/taf"
	"errors"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Errcode int32

const (
	Errcode_SUCCESS    Errcode = 0
	Errcode_OTP_FORMAT Errcode = 51
	Errcode_DB_ERR     Errcode = 96
	Errcode_Freq_Limit Errcode = 97
	Errcode_AUTH_ERR   Errcode = 98
	Errcode_SYS_ERR    Errcode = 99
)

var Errcode_name = map[int32]string{
	0:  "SUCCESS",
	51: "OTP_FORMAT",
	96: "DB_ERR",
	97: "Freq_Limit",
	98: "AUTH_ERR",
	99: "SYS_ERR",
}
var Errcode_value = map[string]int32{
	"SUCCESS":    0,
	"OTP_FORMAT": 51,
	"DB_ERR":     96,
	"Freq_Limit": 97,
	"AUTH_ERR":   98,
	"SYS_ERR":    99,
}

func (x Errcode) String() string {
	return proto.EnumName(Errcode_name, int32(x))
}
func (Errcode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Greet string `protobuf:"bytes,1,opt,name=greet" json:"greet,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetGreet() string {
	if m != nil {
		return m.Greet
	}
	return ""
}

type AuthorizeMsg struct {
	User     string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Clientip string `protobuf:"bytes,3,opt,name=clientip" json:"clientip,omitempty"`
}

func (m *AuthorizeMsg) Reset()                    { *m = AuthorizeMsg{} }
func (m *AuthorizeMsg) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeMsg) ProtoMessage()               {}
func (*AuthorizeMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthorizeMsg) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AuthorizeMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthorizeMsg) GetClientip() string {
	if m != nil {
		return m.Clientip
	}
	return ""
}

type OtpVerifyReq struct {
	Context    string        `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Otp        string        `protobuf:"bytes,2,opt,name=otp" json:"otp,omitempty"`
	Authorizes *AuthorizeMsg `protobuf:"bytes,3,opt,name=authorizes" json:"authorizes,omitempty"`
}

func (m *OtpVerifyReq) Reset()                    { *m = OtpVerifyReq{} }
func (m *OtpVerifyReq) String() string            { return proto.CompactTextString(m) }
func (*OtpVerifyReq) ProtoMessage()               {}
func (*OtpVerifyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OtpVerifyReq) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *OtpVerifyReq) GetOtp() string {
	if m != nil {
		return m.Otp
	}
	return ""
}

func (m *OtpVerifyReq) GetAuthorizes() *AuthorizeMsg {
	if m != nil {
		return m.Authorizes
	}
	return nil
}

type OtpVerifyRsp struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Rescode int32  `protobuf:"varint,2,opt,name=rescode" json:"rescode,omitempty"`
	Errmsg  string `protobuf:"bytes,3,opt,name=errmsg" json:"errmsg,omitempty"`
	Uid     uint64 `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
}

func (m *OtpVerifyRsp) Reset()                    { *m = OtpVerifyRsp{} }
func (m *OtpVerifyRsp) String() string            { return proto.CompactTextString(m) }
func (*OtpVerifyRsp) ProtoMessage()               {}
func (*OtpVerifyRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OtpVerifyRsp) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *OtpVerifyRsp) GetRescode() int32 {
	if m != nil {
		return m.Rescode
	}
	return 0
}

func (m *OtpVerifyRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *OtpVerifyRsp) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "UdbApp.OtpVerifyServer.Request")
	proto.RegisterType((*Response)(nil), "UdbApp.OtpVerifyServer.Response")
	proto.RegisterType((*AuthorizeMsg)(nil), "UdbApp.OtpVerifyServer.AuthorizeMsg")
	proto.RegisterType((*OtpVerifyReq)(nil), "UdbApp.OtpVerifyServer.OtpVerifyReq")
	proto.RegisterType((*OtpVerifyRsp)(nil), "UdbApp.OtpVerifyServer.OtpVerifyRsp")
	proto.RegisterEnum("UdbApp.OtpVerifyServer.Errcode", Errcode_name, Errcode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// Client API for OtpVerify service

type OtpVerifyClient interface {
	SayGreeting(ctx context.Context, in *Request, opts ...map[string]string) (*Response, error)
	OtpVerify(ctx context.Context, in *OtpVerifyReq, opts ...map[string]string) (*OtpVerifyRsp, error)
}

type otpVerifyClient struct {
	s model.Servant
}

func NewOtpVerifyClient(objname string, comm servant.ICommunicator) OtpVerifyClient {
	if comm == nil || objname == "" {
		return nil
	}
	return &otpVerifyClient{s: comm.GetServantProxy(objname)}
}

func (c *otpVerifyClient) SayGreeting(ctx context.Context, in *Request, opts ...map[string]string) (*Response, error) {
	var (
		reply Response
	)

	pbbuf, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}

	_resp, err := c.s.Taf_invoke(ctx, 0, "SayGreeting", pbbuf)
	if err != nil {
		return nil, err
	}

	if err = proto.Unmarshal(_resp.SBuffer, &reply); err != nil {
		return nil, err
	}
	return &reply, nil
}
func (c *otpVerifyClient) OtpVerify(ctx context.Context, in *OtpVerifyReq, opts ...map[string]string) (*OtpVerifyRsp, error) {
	var (
		reply OtpVerifyRsp
	)

	pbbuf, err := proto.Marshal(in)
	if err != nil {
		return nil, err
	}

	_resp, err := c.s.Taf_invoke(ctx, 0, "OtpVerify", pbbuf)
	if err != nil {
		return nil, err
	}

	if err = proto.Unmarshal(_resp.SBuffer, &reply); err != nil {
		return nil, err
	}
	return &reply, nil
}

// Server API for OtpVerify service

type OtpVerifyServer interface {
	SayGreeting(context.Context, *Request) (*Response, error)
	OtpVerify(context.Context, *OtpVerifyReq) (*OtpVerifyRsp, error)
}

type otpVerifyDispatcher struct {
}

func NewOtpVerifyDispatcher() servant.Dispatcher {
	return &otpVerifyDispatcher{}
}

func (_obj *otpVerifyDispatcher) Dispatch(ctx context.Context, _val interface{}, req *taf.RequestPacket) (*taf.ResponsePacket, error) {
	var pbbuf []byte
	_imp := _val.(OtpVerifyServer)
	switch req.SFuncName {
	case "SayGreeting":
		var req_ Request
		if err := proto.Unmarshal(req.SBuffer, &req_); err != nil {
			return nil, err
		}

		_ret, err := _imp.SayGreeting(ctx, &req_)
		if err != nil {
			return nil, err
		}

		if pbbuf, err = proto.Marshal(_ret); err != nil {
			return nil, err
		}

	case "OtpVerify":
		var req_ OtpVerifyReq
		if err := proto.Unmarshal(req.SBuffer, &req_); err != nil {
			return nil, err
		}

		_ret, err := _imp.OtpVerify(ctx, &req_)
		if err != nil {
			return nil, err
		}

		if pbbuf, err = proto.Marshal(_ret); err != nil {
			return nil, err
		}

	default:
		return nil, errors.New("unknow func")
	}
	return &taf.ResponsePacket{
		IVersion:   1,
		IRequestId: req.IRequestId,
		SBuffer:    pbbuf,
		Context:    req.Context,
	}, nil
}

func init() { proto.RegisterFile("OtpVerifyServer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x35, 0xbe, 0xbe, 0xa6, 0xef, 0xb6, 0x48, 0x18, 0xf4, 0x11, 0x0a, 0x62, 0x08, 0x2e, 0x1e,
	0x2e, 0xb2, 0x78, 0xfd, 0x05, 0xb1, 0x1f, 0xba, 0xb0, 0xb4, 0x4c, 0x5a, 0x45, 0x41, 0x6a, 0x9a,
	0x5c, 0xe3, 0x40, 0x9b, 0x99, 0xce, 0x4c, 0xd4, 0xba, 0xf2, 0x57, 0xf9, 0xfb, 0x64, 0xa6, 0x49,
	0x09, 0x62, 0xc5, 0xdd, 0x39, 0x73, 0xee, 0x1c, 0xce, 0xfd, 0x80, 0x27, 0x0b, 0x2d, 0xde, 0xa2,
	0x64, 0x9f, 0x8f, 0x09, 0xca, 0xaf, 0x28, 0x23, 0x21, 0xb9, 0xe6, 0xe4, 0x76, 0x9d, 0x6f, 0x63,
	0x21, 0xa2, 0x3f, 0xd4, 0xf0, 0x29, 0xb8, 0x14, 0x0f, 0x15, 0x2a, 0x4d, 0x08, 0x74, 0xca, 0x74,
	0x8f, 0xbe, 0x13, 0x38, 0x77, 0x37, 0xd4, 0xe2, 0x30, 0x80, 0x1e, 0x45, 0x25, 0x78, 0xa9, 0x90,
	0x3c, 0x86, 0xeb, 0x42, 0x22, 0xea, 0xba, 0xe0, 0x44, 0xc2, 0x0f, 0x30, 0x88, 0x2b, 0xfd, 0x85,
	0x4b, 0xf6, 0x03, 0xe7, 0xaa, 0x30, 0x2e, 0x95, 0x42, 0xd9, 0xb8, 0x18, 0x4c, 0x86, 0xd0, 0x13,
	0xa9, 0x52, 0xdf, 0xb8, 0xcc, 0xfd, 0x87, 0xf6, 0xfd, 0xcc, 0x8d, 0x96, 0xed, 0x18, 0x96, 0x9a,
	0x09, 0xff, 0xea, 0xa4, 0x35, 0x3c, 0xfc, 0xe9, 0xc0, 0xe0, 0x1c, 0x98, 0xe2, 0x81, 0xf8, 0xe0,
	0x66, 0xbc, 0xd4, 0xf8, 0xbd, 0x09, 0xd1, 0x50, 0xe2, 0xc1, 0x15, 0xd7, 0xa2, 0x76, 0x37, 0x90,
	0x4c, 0x00, 0xd2, 0x26, 0x98, 0xb2, 0xd6, 0xfd, 0xfb, 0xe7, 0xd1, 0xdf, 0xc7, 0x10, 0xb5, 0x5b,
	0xa0, 0xad, 0x7f, 0xe1, 0xae, 0x9d, 0x40, 0x89, 0x7f, 0x24, 0xf0, 0xc1, 0x95, 0xa8, 0x32, 0x9e,
	0xa3, 0x4d, 0x71, 0x4d, 0x1b, 0x4a, 0x6e, 0xa1, 0x8b, 0x52, 0xee, 0x55, 0x51, 0x37, 0x58, 0x33,
	0x93, 0xb9, 0x62, 0xb9, 0xdf, 0x09, 0x9c, 0xbb, 0x0e, 0x35, 0xf0, 0xc5, 0x47, 0x70, 0xa7, 0x52,
	0xda, 0x4f, 0x7d, 0x70, 0x93, 0xf5, 0x78, 0x3c, 0x4d, 0x12, 0xef, 0x01, 0x79, 0x04, 0xb0, 0x58,
	0x2d, 0x37, 0xb3, 0x05, 0x9d, 0xc7, 0x2b, 0x6f, 0x44, 0x00, 0xba, 0x93, 0x97, 0x9b, 0x29, 0xa5,
	0xde, 0x27, 0xa3, 0xcd, 0x24, 0x1e, 0x36, 0x6f, 0xd8, 0x9e, 0x69, 0x2f, 0x25, 0x03, 0xe8, 0xc5,
	0xeb, 0xd5, 0x6b, 0xab, 0x6e, 0xad, 0xcd, 0xfb, 0xc4, 0x92, 0xec, 0xfe, 0x97, 0x03, 0x37, 0xe7,
	0x6e, 0xc8, 0x12, 0xfa, 0x49, 0x7a, 0x7c, 0x65, 0xb6, 0xc8, 0xca, 0x82, 0x3c, 0xbb, 0x34, 0x9b,
	0xfa, 0x3e, 0x86, 0xc1, 0xe5, 0x82, 0xfa, 0x42, 0xde, 0xb5, 0xed, 0x2f, 0xce, 0xba, 0xbd, 0xd1,
	0xe1, 0x7f, 0x54, 0x29, 0xb1, 0xed, 0xda, 0x23, 0x1e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x59,
	0x77, 0x3e, 0xd9, 0xdd, 0x02, 0x00, 0x00,
}
